In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from statsmodels.graphics.tsaplots import acf, plot_acf, plot_pacf
from statsmodels.tsa.stattools import acf, adfuller
from statsmodels.tsa.arima_model import ARMA, ARIMA

In [ ]:
df = pd.read_csv('/content/powerconsumption.csv')
df.head()

,Datetime,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
0,1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1,1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2,1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
3,1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
4,1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964

In [ ]:
df.columns

Index(['Datetime', 'Temperature', 'Humidity', 'WindSpeed',
       'GeneralDiffuseFlows', 'DiffuseFlows', 'PowerConsumption_Zone1',
       'PowerConsumption_Zone2', 'PowerConsumption_Zone3'],
      dtype='object')

In [ ]:
df = df.set_index('Datetime')
df.head()

,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
Datetime,,,,,,,,
1/1/2017 0:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
1/1/2017 0:10,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
1/1/2017 0:20,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
1/1/2017 0:30,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
1/1/2017 0:40,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964

In [ ]:
df.index = pd.to_datetime(df.index)

In [ ]:
data = df

In [ ]:
data.head()

,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
Datetime,,,,,,,,
2017-01-01 00:00:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
2017-01-01 00:10:00,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2017-01-01 00:20:00,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
2017-01-01 00:30:00,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
2017-01-01 00:40:00,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 39190 entries, 2017-01-01 00:00:00 to 2017-09-30 03:30:00
Data columns (total 8 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Temperature             39190 non-null  float64
 1   Humidity                39190 non-null  float64
 2   WindSpeed               39190 non-null  float64
 3   GeneralDiffuseFlows     39190 non-null  float64
 4   DiffuseFlows            39190 non-null  float64
 5   PowerConsumption_Zone1  39190 non-null  float64
 6   PowerConsumption_Zone2  39189 non-null  float64
 7   PowerConsumption_Zone3  39189 non-null  float64
dtypes: float64(8)
memory usage: 2.7 MB

In [ ]:
data

,Temperature,Humidity,WindSpeed,GeneralDiffuseFlows,DiffuseFlows,PowerConsumption_Zone1,PowerConsumption_Zone2,PowerConsumption_Zone3
Datetime,,,,,,,,
2017-01-01 00:00:00,6.559,73.8,0.083,0.051,0.119,34055.69620,16128.87538,20240.96386
2017-01-01 00:10:00,6.414,74.5,0.083,0.070,0.085,29814.68354,19375.07599,20131.08434
2017-01-01 00:20:00,6.313,74.5,0.080,0.062,0.100,29128.10127,19006.68693,19668.43373
2017-01-01 00:30:00,6.121,75.0,0.083,0.091,0.096,28228.86076,18361.09422,18899.27711
2017-01-01 00:40:00,5.921,75.7,0.081,0.048,0.085,27335.69620,17872.34043,18442.40964
...,...,...,...,...,...,...,...,...
2017-09-30 02:50:00,17.070,85.2,4.917,0.073,0.133,26894.86726,15825.77963,12973.23800
2017-09-30 03:00:00,17.050,85.2,4.918,0.095,0.107,26786.54867,15747.19335,12890.86823
2017-09-30 03:10:00,16.950,85.5,4.918,0.069,0.126,26843.89381,15807.06861,12843.79980
2017-09-30 03:20:00,16.810,85.8,4.918,0.088,0.119,27047.78761,15735.96674,12867.33401
2017-09-30 03:30:00,16.810,85.9,4.920,0.058,0.137,26907.60000,NaN,NaN

In [ ]:
X1 = data['PowerConsumption_Zone3']

In [ ]:
X = X1[:500]

In [ ]:
size = int(len(X) * 0.66)
size

330

In [ ]:
X.squeeze()

Datetime
2017-01-01 00:00:00    20240.96386
2017-01-01 00:10:00    20131.08434
2017-01-01 00:20:00    19668.43373
2017-01-01 00:30:00    18899.27711
2017-01-01 00:40:00    18442.40964
                          ...
2017-01-04 10:30:00    15250.12048
2017-01-04 10:40:00    15637.59036
2017-01-04 10:50:00    15805.30120
2017-01-04 11:00:00    15892.04819
2017-01-04 11:10:00    16117.59036
Name: PowerConsumption_Zone3, Length: 500, dtype: float64

In [ ]:
X

Datetime
2017-01-01 00:00:00    20240.96386
2017-01-01 00:10:00    20131.08434
2017-01-01 00:20:00    19668.43373
2017-01-01 00:30:00    18899.27711
2017-01-01 00:40:00    18442.40964
                          ...
2017-01-04 10:30:00    15250.12048
2017-01-04 10:40:00    15637.59036
2017-01-04 10:50:00    15805.30120
2017-01-04 11:00:00    15892.04819
2017-01-04 11:10:00    16117.59036
Name: PowerConsumption_Zone3, Length: 500, dtype: float64

In [ ]:
train, test = X[0:size], X[size:len(X)]
history = [x for x in train]
predictions = list()

In [ ]:
# walk-forward validation
for t in range(len(test)):
	model = ARIMA(history, order=(1,1,1))
	model_fit = model.fit()
	output = model_fit.forecast()
	yhat = output[0]
	predictions.append(yhat)
	obs = test[t]
	history.append(obs)
	print('predicted=%f, expected=%f' % (yhat, obs))

/usr/local/lib/python3.7/dist-packages/statsmodels/tsa/arima_model.py:472: FutureWarning:
statsmodels.tsa.arima_model.ARMA and statsmodels.tsa.arima_model.ARIMA have
been deprecated in favor of statsmodels.tsa.arima.model.ARIMA (note the .
between arima and model) and
statsmodels.tsa.SARIMAX. These will be removed after the 0.12 release.

statsmodels.tsa.arima.model.ARIMA makes use of the statespace framework and
is both well tested and maintained.

To silence this warning and continue using ARMA and ARIMA until they are
removed, use:

import warnings
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARMA',
                        FutureWarning)
warnings.filterwarnings('ignore', 'statsmodels.tsa.arima_model.ARIMA',
                        FutureWarning)

  warnings.warn(ARIMA_DEPRECATION_WARN, FutureWarning)

predicted=14251.443911, expected=14342.168670
predicted=14306.730714, expected=14122.409640
predicted=13921.787779, expected=13445.783130
predicted=12851.944758, expected=12595.662650
predicted=11910.719548, expected=11884.337350
predicted=11344.183827, expected=11624.096390
predicted=11478.064998, expected=11780.240960
predicted=11947.598388, expected=11838.072290
predicted=11852.439021, expected=11959.518070
predicted=12063.192465, expected=12167.710840
predicted=12334.954419, expected=12578.313250
predicted=12922.437388, expected=12861.686750
predicted=13052.731033, expected=13110.361450
predicted=13299.229914, expected=13353.253010
predicted=13537.465179, expected=13642.409640
predicted=13871.003690, expected=13885.301200
predicted=14062.484610, expected=14186.024100
predicted=14427.424157, expected=14110.843370
predicted=13989.598565, expected=14139.759040
predicted=14184.836486, expected=14521.445780
predicted=14863.572811, expected=14712.289160
predicted=14819.373899, expected=14989.879520
predicted=15222.901612, expected=15053.493980
predicted=15064.501468, expected=15244.337350
predicted=15414.847771, expected=15388.915660
predicted=15487.155342, expected=15637.590360
predicted=15845.700789, expected=15840.000000
predicted=15985.241882, expected=15897.831330
predicted=15921.065038, expected=16025.060240
predicted=16135.098776, expected=16094.457830
predicted=16135.131190, expected=16285.301200
predicted=16451.037712, expected=16372.048190
predicted=16418.829423, expected=16435.662650
predicted=16482.951423, expected=16614.939760
predicted=16769.000086, expected=16655.421690
predicted=16661.948906, expected=16788.433730
predicted=16907.210891, expected=16632.289160
predicted=16464.746300, expected=16898.313250
predicted=17167.594285, expected=16880.963860
predicted=16818.581467, expected=16915.662650
predicted=16954.775973, expected=16863.614460
predicted=16807.689349, expected=16759.518070
predicted=16671.819470, expected=16771.084340
predicted=16793.349736, expected=16782.650600
predicted=16786.993992, expected=16597.590360
predicted=16426.578846, expected=16325.783130
predicted=16104.595190, expected=16412.530120
predicted=16524.795317, expected=16296.867470
predicted=16171.825303, expected=16366.265060
predicted=16445.633235, expected=16354.698800
predicted=16329.159749, expected=16562.891570
predicted=16751.236130, expected=16632.289160
predicted=16663.159126, expected=16487.710840
predicted=16350.483781, expected=16481.927710
predicted=16495.304941, expected=16429.879520
predicted=16378.499670, expected=16458.795180
predicted=16489.970272, expected=16435.662650
predicted=16407.510622, expected=16499.277110
predicted=16557.993489, expected=16713.253010
predicted=16893.683829, expected=17187.469880
predicted=17583.538782, expected=17852.530120
predicted=18388.598430, expected=19402.409640
predicted=20732.519930, expected=21761.927710
predicted=23769.689674, expected=23866.987950
predicted=25526.744878, expected=24803.855420
predicted=25369.904105, expected=25145.060240
predicted=25354.918657, expected=25347.469880
predicted=25499.299164, expected=25544.096390
predicted=25703.080686, expected=25781.204820
predicted=25977.640961, expected=25700.240960
predicted=25583.517471, expected=25671.325300
predicted=25672.130248, expected=25786.987950
predicted=25901.056838, expected=25740.722890
predicted=25675.185636, expected=25995.180720
predicted=26255.818105, expected=25833.253010
predicted=25628.981772, expected=25746.506020
predicted=25709.405667, expected=25688.674700
predicted=25644.804280, expected=25821.686750
predicted=25960.154924, expected=25891.084340
predicted=25931.958432, expected=26076.144580
predicted=26246.555644, expected=26122.409640
predicted=26135.164792, expected=26157.108430
predicted=26190.914292, expected=26238.072290
predicted=26311.417708, expected=25989.397590
predicted=25742.848651, expected=25729.156630
predicted=25536.420353, expected=25619.277110
predicted=25557.787432, expected=25486.265060
predicted=25376.121796, expected=25226.024100
predicted=25005.181111, expected=24734.457830
predicted=24316.385821, expected=24294.939760
predicted=23966.059489, expected=24190.843370
predicted=24162.085496, expected=23953.734940
predicted=23737.510224, expected=23520.000000
predicted=23155.113540, expected=23034.216870
predicted=22649.759787, expected=22513.734940
predicted=22099.542551, expected=22051.084340
predicted=21697.416309, expected=21443.855420
predicted=20939.222435, expected=20593.734940
predicted=19885.965838, expected=20136.867470
predicted=19845.983942, expected=19575.903610
predicted=19101.372556, expected=19113.253010
predicted=18767.514902, expected=18783.614460
predicted=18538.435865, expected=18176.385540
predicted=17647.097724, expected=17725.301200
predicted=17399.626368, expected=17551.807230
predicted=17449.858366, expected=17280.000000
predicted=17040.690239, expected=16666.987950
predicted=16129.807739, expected=16239.036140
predicted=15936.553344, expected=15892.048190
predicted=15619.888491, expected=15712.771080
predicted=15593.702482, expected=15666.506020
predicted=15643.448696, expected=15371.566270
predicted=15093.595973, expected=14978.313250
predicted=14656.969512, expected=14845.301200
predicted=14779.680272, expected=14775.903610
predicted=14719.931659, expected=14718.072290
predicted=14671.131892, expected=14417.349400
predicted=14138.005773, expected=14174.457830
predicted=13995.882479, expected=14099.277110
predicted=14059.891311, expected=14168.674700
predicted=14238.913986, expected=14081.927710
predicted=13982.212925, expected=14000.963860
predicted=13940.468405, expected=13914.216870
predicted=13840.404216, expected=13850.602410
predicted=13801.333393, expected=13948.915660
predicted=14048.413917, expected=13781.204820
predicted=13599.157511, expected=13839.036140
predicted=13925.380416, expected=13775.421690
predicted=13695.286074, expected=13821.686750
predicted=13877.037285, expected=13821.686750
predicted=13807.558554, expected=13665.542170
predicted=13517.459630, expected=13763.855420
predicted=13881.074266, expected=13827.469880
predicted=13861.478923, expected=14047.228920
predicted=14244.009435, expected=14157.108430
predicted=14219.933584, expected=14214.939760
predicted=14254.099578, expected=14290.120480
predicted=14350.120850, expected=14793.253010
predicted=15252.033972, expected=15163.373490
predicted=15422.134010, expected=15036.144580
predicted=14864.023630, expected=14799.036140
predicted=14606.317772, expected=14648.674700
predicted=14541.492762, expected=14718.072290
predicted=14801.238960, expected=14995.662650
predicted=15238.043926, expected=14839.518070
predicted=14642.596619, expected=14347.951810
predicted=13920.424217, expected=13301.204820
predicted=12390.515357, expected=12526.265060
predicted=11970.426679, expected=11965.301200
predicted=11541.122699, expected=11329.156630
predicted=10806.450292, expected=11392.771080
predicted=11551.300475, expected=11531.566270
predicted=11626.227633, expected=11884.337350
predicted=12193.131484, expected=12098.313250
predicted=12234.841063, expected=12161.927710
predicted=12190.686122, expected=12682.409640
predicted=13161.852998, expected=13416.867470
predicted=14011.107245, expected=13746.506020
predicted=13935.530453, expected=13769.638550
predicted=13750.000769, expected=13937.349400
predicted=14095.999750, expected=14110.843370
predicted=14239.150544, expected=14382.650600
predicted=14609.975216, expected=14718.072290
predicted=14985.810702, expected=14851.084340
predicted=14919.742298, expected=15093.975900
predicted=15306.304361, expected=15250.120480
predicted=15352.173608, expected=15637.590360
predicted=15979.588327, expected=15805.301200
predicted=15893.457018, expected=15892.048190
predicted=15953.918134, expected=16117.590360

In [ ]:
from sklearn.metrics import mean_squared_error
from math import sqrt
import matplotlib.pyplot as plt

In [ ]:
# evaluate forecasts
rmse = sqrt(mean_squared_error(test, predictions))
print('Test RMSE: %.3f' % rmse)

Test RMSE: 230.609

In [ ]:
predictions

[array([14251.44391128]),
 array([14306.73071434]),
 array([13921.78777865]),
 array([12851.94475763]),
 array([11910.71954817]),
 array([11344.18382745]),
 array([11478.06499818]),
 array([11947.59838783]),
 array([11852.43902123]),
 array([12063.19246542]),
 array([12334.95441911]),
 array([12922.43738823]),
 array([13052.73103284]),
 array([13299.22991409]),
 array([13537.46517912]),
 array([13871.00368987]),
 array([14062.4846096]),
 array([14427.42415742]),
 array([13989.5985654]),
 array([14184.83648603]),
 array([14863.57281111]),
 array([14819.37389902]),
 array([15222.90161179]),
 array([15064.50146822]),
 array([15414.84777098]),
 array([15487.15534211]),
 array([15845.70078886]),
 array([15985.24188222]),
 array([15921.06503782]),
 array([16135.09877553]),
 array([16135.13119045]),
 array([16451.03771245]),
 array([16418.82942265]),
 array([16482.95142261]),
 array([16769.00008597]),
 array([16661.94890628]),
 array([16907.21089125]),
 array([16464.7462996]),
 array([17167.59428468]),
 array([16818.58146748]),
 array([16954.77597308]),
 array([16807.6893494]),
 array([16671.81947009]),
 array([16793.34973601]),
 array([16786.9939917]),
 array([16426.57884606]),
 array([16104.59518956]),
 array([16524.7953169]),
 array([16171.8253029]),
 array([16445.63323525]),
 array([16329.15974908]),
 array([16751.23612961]),
 array([16663.15912582]),
 array([16350.48378088]),
 array([16495.30494101]),
 array([16378.49967015]),
 array([16489.97027202]),
 array([16407.51062225]),
 array([16557.99348851]),
 array([16893.68382934]),
 array([17583.53878237]),
 array([18388.5984298]),
 array([20732.51992965]),
 array([23769.68967416]),
 array([25526.74487779]),
 array([25369.90410502]),
 array([25354.91865741]),
 array([25499.29916369]),
 array([25703.08068596]),
 array([25977.64096143]),
 array([25583.51747096]),
 array([25672.13024766]),
 array([25901.05683778]),
 array([25675.18563621]),
 array([26255.81810514]),
 array([25628.98177183]),
 array([25709.40566667]),
 array([25644.80428001]),
 array([25960.15492448]),
 array([25931.95843181]),
 array([26246.55564375]),
 array([26135.16479152]),
 array([26190.91429164]),
 array([26311.41770846]),
 array([25742.84865114]),
 array([25536.42035346]),
 array([25557.78743172]),
 array([25376.12179571]),
 array([25005.1811113]),
 array([24316.38582126]),
 array([23966.05948891]),
 array([24162.08549647]),
 array([23737.51022444]),
 array([23155.11354016]),
 array([22649.7597875]),
 array([22099.54255061]),
 array([21697.41630867]),
 array([20939.22243487]),
 array([19885.96583827]),
 array([19845.98394175]),
 array([19101.37255631]),
 array([18767.51490222]),
 array([18538.4358645]),
 array([17647.09772433]),
 array([17399.62636765]),
 array([17449.85836646]),
 array([17040.69023899]),
 array([16129.80773942]),
 array([15936.5533441]),
 array([15619.88849137]),
 array([15593.70248167]),
 array([15643.44869552]),
 array([15093.59597289]),
 array([14656.96951213]),
 array([14779.68027198]),
 array([14719.93165904]),
 array([14671.13189171]),
 array([14138.00577313]),
 array([13995.88247877]),
 array([14059.8913112]),
 array([14238.91398639]),
 array([13982.2129247]),
 array([13940.46840495]),
 array([13840.40421618]),
 array([13801.33339264]),
 array([14048.41391739]),
 array([13599.15751107]),
 array([13925.38041649]),
 array([13695.28607357]),
 array([13877.03728462]),
 array([13807.55855427]),
 array([13517.45963025]),
 array([13881.07426648]),
 array([13861.47892342]),
 array([14244.00943471]),
 array([14219.93358359]),
 array([14254.09957819]),
 array([14350.12084974]),
 array([15252.03397199]),
 array([15422.13401039]),
 array([14864.02362974]),
 array([14606.31777192]),
 array([14541.49276228]),
 array([14801.23896039]),
 array([15238.04392561]),
 array([14642.59661908]),
 array([13920.4242172]),
 array([12390.51535662]),
 array([11970.42667938]),
 array([11541.1226993]),
 array([10806.45029176]),
 array([11551.3004748]),
 array([11626.22763256]),
 array([12193.13148357]),
 array([12234.84106319]),
 array([12190.68612197]),
 array([13161.85299764]),
 array([14011.10724475]),
 array([13935.53045327]),
 array([13750.00076921]),
 array([14095.99975043]),
 array([14239.15054397]),
 array([14609.97521598]),
 array([14985.81070226]),
 array([14919.74229849]),
 array([15306.30436135]),
 array([15352.17360812]),
 array([15979.58832733]),
 array([15893.45701758]),
 array([15953.91813375])]